spring:
  application:
    name: user-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: food-ordering-client
            client-secret: AdHnkFMg3iA4hsGuuVd2AVXxdE0za8ny
            scope: openid,profile,email
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:7080/realms/food-ordering-realm


server:
  port: 8081