spring:
  application:
    name: user-service

keycloak:
  realm: test
  endpoint: http://localhost:9080
  application:
    client-id: test
    client-secret: AVk9ezqmsWgMetklI0zXsDASuh3gwE0j
  admin-username: admin
  admin-password: admin
server:
  port: 8081